<script lang="ts">
	import {
		Accordion,
		AccordionContent,
		AccordionItem,
		AccordionTrigger
	} from '$lib/components/ui/accordion/index';
	import { SectionContainer } from '..';

	const title = 'Frequently Asked Questions';
	const subtitle = 'Learn more about Imagine AI and our different versions';

	const faqs = [
		{
			question: 'What is Imagine AI?',
			answer:
				'Imagine AI is a web AI art generator that simplifies access to generative art technologies. It empowers users to create unique artwork using AI, cutting-edge algorithms, and deep learning models. The platform offers a user-friendly interface, allowing both beginners and experienced artists to explore various artistic styles and themes without prior expertise. Users can customize and fine-tune their artwork using a range of tools and features, making each creation unique.'
		},
		{
			question: 'Can I use the images generated by the platform for commercial purposes?',
			answer:
				'Yes, you can use the images generated by the platform for commercial purposes. However, you must provide attribution to Imagine AI by including a link to our website in the description or credits section of your artwork.'
		},
		{
			question: 'What are the main features of the Imagine AI app?',
			answer:
				'You can generate images in a variety of styles and themes, and you can also fine-tune the generated images to create your own unique artwork.'
		},
		{
			question: 'What are the differences between Free, Pro, and Premium versions?',
			answer:
				'You can generate limited images with the Free version, and you can upgrade to Pro or Premium to unlock more features and generate unlimited images.'
		},
		{
			question: 'Can I cancel my Plan?',
			answer: `Yes, you can cancel your Plan at any time. Your existing data will be preserved.`
		},
		{
			question: "What is Imagine's refund policy?",
			answer:
				'We do not offer refunds for our products. However, if you are not satisfied with your purchase, please contact us and we will do our best to assist you.'
		}
	];
</script>

<SectionContainer {title} {subtitle} id="faq" contentClass="max-w-3xl">
	<Accordion class="w-full space-y-2">
		{#each faqs as faq, index}
			<AccordionItem value={`item-${index}`} class="border rounded-lg">
				<AccordionTrigger
					class="text-left items-start px-4 hover:no-underline hover:bg-muted/50 transition-colors"
				>
					<span>{faq.question}</span>
				</AccordionTrigger>
				<AccordionContent>
					<div class="p-4 text-muted-foreground">
						{faq.answer}
					</div>
				</AccordionContent>
			</AccordionItem>
		{/each}
	</Accordion>
</SectionContainer>
